const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'/tmp/dinastia-chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote']});
 const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4179/?artifact');await page.getByRole('button',{name:'Usar Voo de Serafim',exact:true}).waitFor();
 await page.getByRole('button',{name:'Usar Voo de Serafim',exact:true}).click();await page.getByRole('status').filter({hasText:'Voo de Serafim utilizado.'}).waitFor();
 assert.equal(await page.evaluate(()=>window.__testStore.get('sheets/necro').vigos),8);
 const peer=await context.newPage();await peer.goto('http://127.0.0.1:4179/?artifact');await peer.getByRole('button',{name:'Usar Intocável',exact:true}).waitFor();
 await page.getByRole('button',{name:'Usar Intocável',exact:true}).dblclick();
 await page.waitForFunction(()=>window.__testStore.get('sheets/necro').vigos===5);
 await peer.waitForFunction(()=>window.__testStore.get('sheets/necro').vigos===5);
 assert.equal(await page.evaluate(()=>window.__testStore.get('sheets/necro').cooldowns['artifact:artefato-2:dodge']),3);
 assert.equal(await page.getByRole('button',{name:'Em recarga: 3 turno(s)',exact:true}).isDisabled(),true);
 await page.evaluate(()=>window.__testStore.set('sheets/necro',{...window.__testStore.get('sheets/necro'),agilidade:7,cooldowns:{},equip_mao_dir:{agilidade:99}}));
 await page.waitForFunction(()=>[...document.querySelectorAll('.artifact-powers button')].every(b=>b.disabled));
 assert.match(await page.locator('.artifact-requirements').innerText(),/\+3 Agilidade/);
 const power={_artifactId:'artefato-2',_artifactPowerId:'flight',id:'artifact:artefato-2:flight',nome:'Voo de Serafim',custo:0};
 assert.equal(await page.evaluate(power=>window.__artifactUse(power,window.__testStore.get('sheets/necro')),power),false);
 await page.evaluate(()=>window.__testStore.set('sheets/necro',{...window.__testStore.get('sheets/necro'),agilidade:8,percepcao:3}));
 assert.equal(await page.evaluate(power=>window.__artifactUse(power,window.__testStore.get('sheets/necro')),power),false);
 await page.evaluate(()=>window.__testStore.set('sheets/necro',{...window.__testStore.get('sheets/necro'),percepcao:4,artefato_id:''}));
 assert.equal(await page.evaluate(power=>window.__artifactUse(power,window.__testStore.get('sheets/necro')),power),false);
 assert.equal(await page.evaluate(power=>window.__artifactUse(power,{id:'other',artefato_id:'artefato-2'}),power),false);
 await page.evaluate(()=>window.__testStore.set('sheets/necro',{...window.__testStore.get('sheets/necro'),artefato_id:'artefato-2'}));
 await page.evaluate(()=>window.__testStore.set('config/artefatos',{unlocked:{'artefato-2':false}}));
 assert.equal(await page.evaluate(power=>window.__artifactUse(power,window.__testStore.get('sheets/necro')),power),false);
 await page.evaluate(()=>window.__testStore.set('config/artefatos',{unlocked:{'artefato-2':true}}));
 await page.evaluate(()=>window.__testStore.set('config/combat',{active:true}));
 await page.evaluate(()=>window.__testStore.set('config/combat_state',{initiative:[{id:'p_other',type:'player'}],turnIdx:0}));
 assert.equal(await page.evaluate(power=>window.__artifactUse(power,window.__testStore.get('sheets/necro')),power),false);
 await page.evaluate(()=>window.__testStore.set('config/combat_state',{initiative:[{id:'p_necro',type:'player'}],turnIdx:0}));
 assert.equal(await page.evaluate(power=>window.__artifactUse(power,window.__testStore.get('sheets/necro')),power),true);
 // Same powers available from the ability drawer.
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('dinastia:adventure-panel',{detail:{panel:'abilities'}})));
 await page.locator('.g3-ability-drawer .artifact-powers').waitFor({state:'attached'});await page.locator('.g3-ability-drawer .artifact-powers').scrollIntoViewIfNeeded();
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.locator('.artifact-sheet-panel').evaluate(e=>e.getBoundingClientRect().right<=innerWidth),true);
 await page.goto('http://127.0.0.1:4179/?artifact&book');await page.getByRole('button',{name:'Os 6 Artefatos'}).click();
 await page.setViewportSize({width:1280,height:900});await page.getByRole('button',{name:'Próxima página'}).click();await page.getByRole('heading',{name:/Sandaliers Six/i}).waitFor();
 assert.match(await page.locator('.livro-stage').innerText(),/8 pontos base de Agilidade e 4 de Percepção/);
 assert.match(await page.locator('.livro-stage').innerText(),/Voo de Serafim/i);
 assert.match(await page.locator('.livro-stage').innerText(),/Intocável/i);
 assert.deepEqual(errors,[]);console.log('PASS artifact: bearer access, natural bonus boundaries, cost/cooldown, two-client sync, sealed/turn gates, book and mobile');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
