const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'/tmp/dinastia-chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote']});
 const context=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'});
 const page=await context.newPage(),errors=[];page.setDefaultTimeout(10000);page.on('pageerror',error=>errors.push(error.message));
 await page.goto('http://127.0.0.1:4179/?visitors');
 await page.getByRole('button',{name:'Visitante',exact:true}).click();
 await page.getByLabel('Nome do visitante').selectOption('guest-a');
 await page.getByLabel('Senha do visitante').fill('incorreta');
 await page.getByRole('button',{name:'Entrar como visitante',exact:true}).click();
 await page.getByText('Senha incorreta para este visitante.').waitFor();
 await page.getByLabel('Senha do visitante').fill('Senha123');
 await page.getByRole('button',{name:'Entrar como visitante',exact:true}).click();
 await page.getByLabel('Meu personagem',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('Meu personagem',{exact:true}).locator('option').count(),3);
 assert.equal(await page.getByText('Personagem secreto B',{exact:true}).count(),0);
 assert.equal(await page.locator('.ad-party').getByText('Necromante',{exact:true}).count(),0);
 await page.getByLabel('Meu personagem',{exact:true}).selectOption('guest-2');
 await page.getByRole('button',{name:'Meus personagens',exact:true}).click();
 await page.getByRole('heading',{name:'Personagens do visitante',exact:true}).waitFor();
 await page.getByRole('button',{name:'Maga visitante',exact:true}).click();
 await page.getByRole('button',{name:'Cavaleiro visitante',exact:true}).waitFor();
 for(const width of [360,390,430,768,1280]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 // Access revocation is live and does not rely on cached role flags.
 await page.evaluate(()=>window.__testStore.set('visitors/guest-a',{...window.__testStore.get('visitors/guest-a'),active:false}));
 await page.getByRole('heading',{name:'Quem atravessa o Véu?',exact:true}).waitFor();
 await page.screenshot({path:'/tmp/dinastia-visitor-gate.png'});
 await context.close();
 const adminContext=await browser.newContext({viewport:{width:1280,height:900}});const admin=await adminContext.newPage();admin.on('pageerror',error=>errors.push(error.message));
 await admin.goto('http://127.0.0.1:4179/?visitor-admin');
 await admin.getByLabel('Nome do visitante',{exact:true}).fill('Teste visitante');
 await admin.getByLabel('Senha do novo visitante').fill('SenhaTeste');
 await admin.getByRole('button',{name:'Criar visitante',exact:true}).click();
 await admin.getByRole('heading',{name:'Teste visitante',exact:true}).waitFor();
 await admin.getByLabel('Nome do personagem',{exact:true}).fill('Personagem de teste');
 await admin.getByRole('button',{name:'Adicionar personagem',exact:true}).click();
 await admin.getByRole('button',{name:'Personagem de teste',exact:true}).waitFor();
 await adminContext.close();
 const mapContext=await browser.newContext({viewport:{width:1280,height:900}});const map=await mapContext.newPage();map.on('pageerror',error=>errors.push(error.message));
 await map.goto('http://127.0.0.1:4179/?map&combat&map-summons');
 await map.locator('.summon-mini-available button').click();
 await map.locator('.summon-mini-sheet').waitFor();
 await map.getByLabel('Diminuir HP de Corvo').click({clickCount:3});
 await map.waitForFunction(()=>window.__testStore.get('combat_summons/summon_necro_bird')?.hp===44);
 await map.locator('.summon-mini-sheet output').filter({hasText:'44/47'}).waitFor();
 await map.getByLabel('Aumentar HP de Corvo').click();
 await map.locator('.summon-mini-sheet output').filter({hasText:'45/47'}).waitFor();
 await map.getByLabel('Diminuir VC de Corvo').click();
 await map.locator('.summon-mini-sheet output').filter({hasText:'2/3'}).waitFor();
 await map.locator('.summon-mini-actions button').click();
 await map.waitForFunction(()=>window.__testStore.get('combat_summons/summon_necro_bird')?.vigos===1);
 await map.screenshot({path:'/tmp/dinastia-summon-mini.png'});
 await map.locator('.summon-mini-sheet').getByRole('button',{name:'Guardar',exact:true}).click();
 await map.locator('.summon-mini-sheet').waitFor({state:'detached'});
 await map.locator('.summon-mini-available button').click();
 await map.locator('.summon-mini-sheet output').filter({hasText:'45/47'}).waitFor();
 assert.equal(await map.evaluate(()=>window.__testStore.get('combat_summons/summon_necro_bird').vigos),1);
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,checks:['visitor login and invalid password','two owned characters; no other sheets','five viewport widths','live revocation','master creates visitor and character','summon release, rapid HP edits, VC, action, store and release without reset'],errors}));
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
